worker_processes auto;

events {
    worker_connections 1024;
}

# --- PARTIE 1: RTMP (Pour OBS / Streaming) ---
rtmp {
    server {
        listen 1935;
        chunk_size 4096;

        application live {
            live on;

            # Hado homa li kaysawbo HLS
            hls on;
            hls_path /tmp/hls;
            hls_fragment 1;
            hls_playlist_length 4;
        }
    }
}

# --- PARTIE 2: HTTP (Pour Angular / Web) ---
http {
    server {
        listen 80;

        location /hls {
            # Hna kanwarru l Navigateur kifach yqra les fichiers video
            types {
                application/vnd.apple.mpegurl m3u8;
                video/mp2t ts;
            }
            root /tmp;

            # Headers bach Angular ma-ybloquich (CORS)
            add_header Cache-Control no-cache always;
            add_header Access-Control-Allow-Origin * always;
            add_header Access-Control-Allow-Methods "GET, HEAD, OPTIONS" always;
            add_header Access-Control-Allow-Headers "*" always;

            # Pour les requêtes prévol (OPTIONS) côté navigateur
            if ($request_method = OPTIONS) {
                return 204;
            }
        }
    }
}